### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by paineleffler** [paineleffler/cage_ify#2]
Traceback (most recent call last):
  File "cage_ify.py", line 58, in <module>
    main()
  File "cage_ify.py", line 17, in main
    deleteOldImages()
  File "cage_ify.py", line 48, in deleteOldImages
    for the_file in os.listdir(folder):
OSError: [Errno 2] No such file or directory: '/Users/$USER/Desktop/'
30:45: execution error: Finder got an error: Can’t set file "0.jpg" of desktop to file "0.jpg" of desktop. (-10006)

**Comment by samrose3** [comment]
maybe adding this to your script would inject the $USER env variable into the python script
```
sed -i "" "s/USER/$USER/g" get_images.py
```

sed magic :tophat: :rabbit2:

**Comment by paineleffler** [comment]
I tried doing this, however I don't think I did it right. But as a quick fix I did getpass.getuser()

**Comment by paineleffler** [comment]
actually i think it did work, i just when back to check my python file and it had replaced USER with paine

**Comment by samrose3** [comment]
I do agree and I did see the `getpass.getuser()` method. That actually might be a better option since the script will always get the right user before getting the images. Good idea.
